version: '3.8'

services:
  mongo1:
    image: mongo:latest
    restart: always
    hostname: mongo1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=guyrt
      - MONGO_INITDB_ROOT_PASSWORD=bob
      - MONGO_REPLICA_SET_NAME=rs0
    volumes:
      - mongo1-data:/data/db
      - mongo-keyfile:/etc/mongo-keyfile
    command: ["--replSet", "rs0", "--keyFile", "/etc/mongo-keyfile/mongo-keyfile"]
    networks:
      - mongo-cluster

  mongo2:
    image: mongo:latest
    restart: always
    hostname: mongo2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=guyrt
      - MONGO_INITDB_ROOT_PASSWORD=bob
      - MONGO_REPLICA_SET_NAME=rs0
    volumes:
      - mongo2-data:/data/db
      - mongo-keyfile:/etc/mongo-keyfile
    command: ["--replSet", "rs0", "--keyFile", "/etc/mongo-keyfile/mongo-keyfile"]
    networks:
      - mongo-cluster

  mongo3:
    image: mongo:latest
    restart: always
    hostname: mongo3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=guyrt
      - MONGO_INITDB_ROOT_PASSWORD=bob
      - MONGO_REPLICA_SET_NAME=rs0
    volumes:
      - mongo3-data:/data/db
      - mongo-keyfile:/etc/mongo-keyfile
    command: ["--replSet", "rs0", "--keyFile", "/etc/mongo-keyfile/mongo-keyfile"]
    networks:
      - mongo-cluster

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=guyrt
      - ME_CONFIG_MONGODB_ADMINPASSWORD=bFANwo1eaXQT6xJL5FH5
      - ME_CONFIG_MONGODB_SERVER=mongo1
    networks:
      - mongo-cluster

  setup-replica:
    image: mongo:latest
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - mongo-cluster
    command: >
      bash -c "
        sleep 10;
        mongo --host mongo1:27017 -u guyrt -p bob --authenticationDatabase admin --eval 'rs.initiate({
          _id: \"rs0\",
          members: [
            { _id: 0, host: \"mongo1:27017\" },
            { _id: 1, host: \"mongo2:27017\" },
            { _id: 2, host: \"mongo3:27017\" }
          ]
        })';
      "

volumes:
  mongo1-data:
    driver: local
  mongo2-data:
    driver: local
  mongo3-data:
    driver: local
  mongo-keyfile:
    driver: local

networks:
  mongo-cluster:
    driver: bridge
