version: '3'
services:
  mongo:
    image: mongo:6
    container_name: mongo 
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: admin 
    entrypoint:
      - bash
      - -c
      - |
          cp /keyfile /mongo_keyfile
          chmod 400 /mongo_keyfile
          chown 999:999 /mongo_keyfile
          exec docker-entrypoint.sh $$@
    command: "mongod --bind_ip_all --replSet rs0 --keyFile /mongo_keyfile"
    volumes:
      - ./keyfile:/keyfile

  mongo-setup:
    image: mongo:6
    container_name: mongo_setup
    depends_on:
      - mongo
    restart: on-failure
    entrypoint: ["/bin/bash", "/setup_mongo.sh"]
    volumes:
      - ./setup_mongo.sh:/setup_mongo.sh
